#!/usr/bin/env bash
set -euox pipefail

# TODO check if 'podman' is available and use that if so, otherwise run with 'docker'
podman build -t cloudshell-fedora .

# TODO -t cloudshell-debian ... the problem is -t only works for the last image, so must parse output and map
