# Keep this in sync with Dockerfile-Fedora

FROM golang AS gotty-build
RUN go get github.com/yudai/gotty \
 && echo GOPATH=$GOPATH && $GOPATH/bin/gotty || true

FROM debian:latest AS debian-updated
RUN apt-get update -y

FROM debian-updated AS debian-plus
RUN apt-get install -y sudo git hub findutils less htop \
                   nano bash-completion zsh fish net-tools \
                   tmux psmisc

FROM debian-plus AS cloudshell-debian
COPY --from=gotty-build /go/bin/gotty /gotty
COPY ./init /init
ENV TERM=xterm-256color
EXPOSE 8080
ENTRYPOINT /gotty --credential "$USER_ID":"$USER_PWD" --permit-write /init tmux new -A -s CLOUD
